In [1]:
import numpy as np


In [2]:
digit = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [3]:
print(digit)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
digit.ndim

2

In [6]:
a = np.array(42)
b = np.array([1,2,3,4,5])
c = np.array([[1,2,3], [4,5,6], [7,8,9]])
d = np.array([[[1,2,3], [4,5,6]],[[6,7,4], [9,8,2]]])

In [7]:
print(a)
print(b)
print(c)
print(d)

42
[1 2 3 4 5]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[[1 2 3]
  [4 5 6]]

 [[6 7 4]
  [9 8 2]]]


In [8]:
print(a.ndim, b.ndim, c.ndim, d.ndim)

0 1 2 3


In [9]:
print(a.shape, b.shape, c.shape, d.shape)

() (5,) (3, 3) (2, 2, 3)


In [11]:
arr = np.array([1,2,3,4], ndmin=1)
print(arr)
print(arr.ndim)
print(arr.shape)

[1 2 3 4]
1
(4,)


In [12]:
arr = arr.reshape((2,2))
print(arr)
print(arr.shape)

[[1 2]
 [3 4]]
(2, 2)


In [13]:
arr[0]

array([1, 2])

In [14]:
arr[0][0]

1

In [15]:
arr[1][0]

3

In [18]:
arr[1][0] = arr[0][0]+6

In [19]:
arr

array([[1, 2],
       [7, 4]])

In [21]:
a = np.array([[1,2,2,3,4], [5,6,7,8,9]])
b = np.array([[6,5,3,2,1], [9,5,8,7,3]])
a+b

array([[ 7,  7,  5,  5,  5],
       [14, 11, 15, 15, 12]])

In [27]:
vals = np.random.randn(0, 100)

In [28]:
vals

array([], shape=(0, 100), dtype=float64)

In [30]:
rand_vals =[np.random.randint(100, size=(3, 5)) for i in range(0, 10)]

In [31]:
rand_vals

[array([[11, 91, 30, 38, 77],
        [40, 46, 19, 93, 44],
        [53, 67, 86, 70, 52]]),
 array([[26, 83, 78, 27, 40],
        [54, 52, 45, 92, 36],
        [25,  1, 81, 13, 39]]),
 array([[84, 16, 55, 66, 83],
        [52, 68,  1, 32, 68],
        [72, 61, 38, 64, 86]]),
 array([[89, 74, 62, 91, 24],
        [ 5, 71,  7,  1, 27],
        [33, 79, 73, 16,  6]]),
 array([[23, 27, 48, 44, 90],
        [87, 93, 24, 20, 58],
        [15, 21, 61, 32, 34]]),
 array([[90,  8, 73, 34, 92],
        [54, 86, 52, 77, 22],
        [46, 89, 89, 29, 77]]),
 array([[32, 55, 17, 77, 69],
        [99, 28, 34, 33, 64],
        [10, 57, 30, 33, 50]]),
 array([[81, 56, 61, 72, 42],
        [63, 50, 15, 21, 95],
        [17, 27, 71, 60, 74]]),
 array([[66, 28, 49, 57, 57],
        [94, 96, 82, 98, 64],
        [ 5, 77, 27, 22,  5]]),
 array([[28,  2,  7, 58, 94],
        [16, 92, 60, 30, 81],
        [25,  9, 48, 40, 53]])]